name: Tuto
main: fr.ng.ibalix.tuto.Tuto
version: 1.0
author: iBalix
commands:
   hello:
      description: This is a demo command.
      usage: /hello
   hello2:
      description: This is a demo command.
      usage: /hello2
   testperm:
      description: This is a demo command.
      usage: /testperm
   stone:
      description: This is a demo command.
      usage: /testperm
   stoneoff:
      description: This is a demo command.
      usage: /testperm