name: NationsArcade
main: fr.ng.ibalix.nationsarcade.NationsArcade
version: 1.0
author: iBalix
commands:
   vote:
      description: Voter pour une map
      usage: /vote <map>
   game:
      description: Rejoindre la partie en cours
      usage: /game
   nareload:
      description: Reload la config
      usage: /nareload
   joingame:
      description: Join a game
      usage: /joingame
depend: [War]